---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: pacman-secret
  namespace: pacman
spec:
  encryptedData:
    pass: AgBXGEwKXSMDPktXKnqQB6Xyvah1JUxu6R1mX0pDSjlzIjCQjVfQ/EIZzryVXmOGHY925dfQk8R7wTbO4QpEZqlD2fm1cnGHIvi78HVKMbDKiOyH90kOphLEK8/C2PmOZ/dLvQwSVD9T4ZIpmAycqaGb4P4VqaSuPTNzooIH2CHYexQen8ufCvFBlutXkDNcV7dpIX0wwU1/jEaRXw6/N6w680n+uxlCijSGeb0zBbpEnKChDCq3CIXP9NhPf17PTPupUFKXUxV0nysyiueo6++KfKkXEc1ebDqDdGasm+ruNGVSJMAqb5QFFb90EanW377BvlnRmVv5a9NkbZvHQliNlW5Ay6tMH0Q6CbJolvHWNV+frM5xksC+tt5mGes5BxWlsG3VXb0VAOFyf9nfpFHsx99DmNdpzxteTKH169bWJezQdzaO3CAnJxx1CiZK72sboFk6fdxSEUp/0PRhqLexgttAJlovkUy1V2ehobxpEZkn0BfW/WzN3VOhSqMMipjyzXkYuvL+pV/7gTFjNUTB9Jm6l8IeTiEzQRCmmtmDqKAeGNpXvDx0bvMaCmMOWk1yEcN3f3vCiws4jbt2bocodTTKVGTLS73xSK5hAI2YEu+TAsZ5Ci1+wP7CEgDTN2ZlPWu+Fgp/F2gDKlAEbodes1koUtqfHYzNA7/ysHdd81lVXHonvNXKAvP7FszseUm62M+sHzI=
    user: AgB5q1jjr+NGfiSWKAqKtv3VvZM4VQPtkz+i0RUh4sYM/4krFO5qOGUuSzw9RfOAItCcZczciLRXVNLcgW3+xN63gCu4tzWC46LvbAsewMAenrCpOLMPHG6sbtEYSTvTuAnybAClA0hPpdfbQYx123/ltpAqTSC2/mXEnbzKFWffICgzjiPWvWqpRQHIuJ97oPle24oqy/ug5MwqN+Yszqk3H/+SYQFgM65N9Vvw4zAZw1mcbPAZ6KSlpvGgADFa2362dKOTUC5EbJSTB070H7ux4fERE2jNCVmhmFSikyvWbBWX4u/WFppW7wN1WCmNujVvY5mIIGLjeECWUymI3I768VWsvCMcYy3hDCP6lmbXr4GwsXlzj1Ef2uh46uFCSXLjNhBA4f0HQKzm6FkGTKq7MITe8nvm3ayDdyitFklZyo42bPigE9U8Ol+5ZsR9+2jQ8up++wfQCYd+3akdoL9S7+UCYVSGJXq4s+4o1fFuCtTeuGiVp3GVkaSYESYa7IHGwg71hv/sUBDsDbE/wEF5upqDSj+OHx06YFvQwZeBhqLQOHJ0qoO1uO4Czl0/FwvhS2um2tgYtB+tEJ5mqMxc837+WelOu6OrFpehbA6wlCN3rrpfRuyeITDm7Fo4szyM+qS1xdTkwBSprWrP4uJvi4Q5Z9EsnLTuiUl73sPNOpKAjXhGyZLROKVlXxC7kIosVspKSXk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      managedFields:
        - apiVersion: v1
          fieldsType: FieldsV1
          fieldsV1:
            f:data:
              .: {}
              f:pass: {}
              f:user: {}
            f:type: {}
          manager: kubectl
          operation: Update
          time: "2025-01-23T14:50:53Z"
      name: pacman-secret
      namespace: pacman
    type: Opaque
